# Generated by Django 4.0.1 on 2022-02-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('SubCategory1', models.CharField(blank=True, max_length=200, null=True)),
                ('SubCategory2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.tag')),
            ],
        ),
    ]
